# Generated by Django 5.2.5 on 2025-08-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSupermercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
